graphql:
  packages:
    - "com.mika.tutorialKotlinGraphQL"

spring:
  r2dbc:
    initialization-mode: never
    initialize=false:
    url: r2dbc:mysql://127.0.0.1:3306/tutoKotlinGraphQLdb?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
